import { Providers } from "./providers";
import { titleFont } from "../config/fonts";
import "./globals.css";

export const metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${titleFont.className} antialiased tracking-widest text-slate-100 uppercase`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
